tomasbedrich/pycaching

pycaching/cache.py
I had some problems with the latest version, probably due to changes at geocaching.com
Earthcache threw an exception '137 not a valid cache type'. If I removed the old "earthcache" that threw the same exception so both are in there now. Tested against http://www.geocaching.com/geocache/GC5JQ55_granit
Abandoned Structure attribute was not detected for http://www.geocaching.com/geocache/GC4QGMZ_punkknackarkalendern-4-7-tribute-to-sid-vicious
It seems like both lower case image names and camel case images exists right now. To support both all attribute names are made lower case in this pull request.
=> Cache fetching

pycaching/geocaching.py
The issue seems to only be with event caches.
Tested with http://www.geocaching.com/geocache/GC5R0P3_sankt-goran-och-draken among others
=> Caches lacking favorites now works

README.rst, pycaching/cache.py, pycaching/geocaching.py, test/test_cache.py
The cache object now stores info about the trackables it contains. If the cache has trackables, the url to the list of those trackables is stored and when the user tries to access the trackables-property the actual list is loaded. This to reduce time loading caches for "normal" use.
New example use added. (Listing nearby caches that contain trackables.)
=> Caches with trackables

pycaching/cache.py, pycaching/geocaching.py, pycaching/trackable.py, test/test_cache.py, test/test_geocaching.py, test/test_trackable.py
This is a bit of a cleanup making the trackable handling a bit more inline with the rest of the pycaching module and reduces clutter in the Cache class. Now when loading the cache the trackable page is parsed and trackables are quick-loaded.
(Previously trackables were not loaded at all when parsing a cache, instead a link to the trackable search page for the cache was stored and loaded together with all trackables when the trackable property was requested.)
=> Quickloaded trackables

pycaching/cache.py, pycaching/geocaching.py, test/test_cache.py
* Geocaching class extended with load_logbook() method.
* Cache class extended with getter and setter for logbook member
* Basic test for logbook getter added
This should resolve #30. The logbook is right now always loaded when the cache is loaded, this can easily be changed to be loaded only when the log is accessed by storing the userToken in the cache instead of reading the log directly.
The code for reading the number of logs to request is a bit ugly and any suggestion of improvement is appreciated.
=> Added logbook loading for caches.

pycaching/geocaching.py
Make sure location_url has an (empty) value, to prevent an exception 
(tested with TB6JYV5)
=> Prevent exception when location_url has no value

pycaching/cache.py
When trying to reproduce this issue I tried loading an archived event that I'd logged as attended for tests. Archived caches aren't search-able and thus normal loading failed. When setting the url manually I got NameError. This pull request fixes that small issue.
=> Corrected typo preventing loading cache from url

pycaching/cache.py, test/test_cache.py
This adds some tests related to post_log().
09e0409 is simple enough, just tests the property ```log_page_url```
e7a19f4 verifies that the log text field is not an empty string. The small change in ```pycaching/cache.py``` should be added even if the test is a bit clumsy.
8f2adef is a test for the log-type matching code and might be overkill since it requires some restructuring, mocks out a lot and is generally messy.
=> Post log tests

pycaching/geo.py
Calculate longitude span for area, then get such zoom level, where tile width
is above this span.
Previous implementation loads unnecessarily large tiles, if area is located at
the border of two large tiles.  Hence, download more smaller tiles (typically
1, 2 or 4).
=> Calculate default zoom level in quick search

pycaching/cache.py
Premium members can now see if a cache is only available for premium members.
Can be useful to know even if it won't affect loading the cache. For example if you're compiling a list for a geocaching trip and all members aren't premium.
=> Sets pm_only status correctly for premium members

pycaching/cache.py, test/test_cache.py
The simple solution for #37. A new property ```orginal_location``` is added to the Cache-object.
As I implemented this I started thinking that this might not be the best way, maybe we should intruduce a dictionary named additional_locations which contains any additional coordinates. Since many caches have extra locations such as coordinates for parking or for the different steps in a multi-cache.
Any thoughts?
=> Mystery original coords

pycaching/cache.py
Loading a non-existing cache returns a 404-page and will raise a ValueError when the GC-code is determined. To fix this the ValueError is caught and the expected LoadError is raised.
This popped up as an issue when I tried to get the tests for my other pull-request running.
=> Fix failing load non-existing cache test

docs/api.rst, pycaching/cache.py, test/test_cache.py
Additional Waypoint table is parsed into a dict of namedTuples containing the information for each location.
This pull request is a starting point for discussion for issue #58.
=> Adds support for handling additional locations

pycaching/cache.py
When parsing waypoints from the HTML table it is not guaranteed that the location is in proper format, e.g. hidden stages have '???' in the location field (see e.g. GC3WTTZ). This caused an unhandled exception in `Waypoint.from_html()`.
Fixing this issue by catching the `ValueError` raised by the `geopy.Point()` initializer and setting the waypoints location to `None`.
=> Catch exception if waypoint location is invalid

pycaching/cache.py, test/test_cache.py
Implement cache details loading by GUID according to issue #29 
- Add method to retrieve a caches GUID
- Add method to load all cache details from its _print-page_ (with a few exceptions of properties that are not listed there)
- Add `id_` argument to `Waypoints.from_html()` allowing to specify the html-id of the waypoint table to parse
=> Issue29 cache loading by GUID

test/cassettes/geo_location_empty.json, test/cassettes/geo_location_existing.json, test/cassettes/geo_location_nonexisting.json, test/cassettes/geocaching_shortcut_geocode.json, test/test_geo.py, test/test_geocaching.py
Fixes #101, please review @weinshec.
=> Use another town to test geocoding

test/__init__.py, test/test_cache.py, test/test_geo.py, test/test_geocaching.py, test/test_trackable.py, test/test_util.py
Fixes #114, I believe.
This changes so that each test class has its own session, `Geocaching` instance, and recorder. Hopefully this will improve the experience of recording new tests.
=> Improve networked tests

pycaching/geocaching.py, test/test_geocaching.py
see #117 
I have changed the function my_logs() so that if cache can be read by guid it is read by guid and otherwise -- i. e. if the cache is only for premium members -- it reads the cache by the GC code. So my_logs() doesn't throw an error and you can get the information of the caches you have found before the PMonly cache. It is even possible to get some information on the PMonly cache by cache.load_quick().
=> Avoid stopping function my_logs() at premium cache

pycaching/geo.py, test/test_geo.py
Return the correct hemisphere for an input string with lowercase characters such as "N32 46.000 w111 38.555"
=> Correct lowercase coordinates

pycaching/log.py
I run into type of log which is currently not supported. It seem like a duplicate of Post Reviewer Log but with id 68.
Cache where I encountered this problem: https://www.geocaching.com/geocache/GCT686
=> Add secondary ID for post_reviewer_note log type

README.rst, pycaching/geocaching.py, test/test_geocaching.py
The credentials file can now also hold a list of credentials.
Providing the username when loging is trying to map it to the
possible multiple supplied creditials.
Signed-off-by: gcbor <gcbor@gmx.de>
=> Add support for multi user in credentials file

pycaching/util.py
This fixes some date formatting issues on some systems as reported in #130. It seems like Windows does not like the `-` flag for date formatting which is stated as platform-dependent inside the Python docs.
This should close #130.
=> Fix date formatting

pycaching/cache.py, test/test_cache.py
This adds loaders for the log counts using the cache details and the print pages, as per #128.
At the moment this introduces some duplicate code where both pages share the implementation. I am not sure whether it makes sense to combine them into one method or move them to a `LogCount` class inside the `log` module.
=> Add log counts loaders

test/test_geo.py
This fixes the blocks test by setting the UTF-8 encoding when opening the JSON file. Otherwise the corresponding test may fail on Windows because the default encoding (in my case CP-1252) is used which cannot handle some of the characters:
```
======================================================================
ERROR: Parse locally stored grid and compare to expected results
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\Python\lib\unittest\mock.py", line 1195, in patched
return func(*args, **keywargs)
File "C:\Me\GitHub\pycaching\test\test_geo.py", line 207, in test_blocks
mock_utfgrid.return_value = json.load(f)
File "C:\Python\lib\json\__init__.py", line 293, in load
return loads(fp.read(),
File …
```
=> Set correct file encoding for Windows

README.rst, pycaching/cache.py, setup.py
Fix #139 regarding the retrieval of JavaScript objects for bs4 >= 4.9 . This raises the minimum bs4 version to 4.9 as well.
Additionally some typos have been fixed inside the README and a paragraph regarding updating a test cassette has been added.
=> Fix script retrieval to work with bs4 >= 4.9

docs/conf.py
=> Update docs copyright

pycaching/geocaching.py
A bug fix for issue #144 
The while loop will be stopped if there no table rows elements in loaded results
=> Issue 144 stop search

.coveralls.yml, .travis.yml
This adds Windows support for the Travis tests (see #134).
=> Add Windows runner configuration

pycaching/cache.py, pycaching/log.py, test/test_cache.py
I have extended `Log` class with `.uuid` field - unique (server side) log identifier. It can be used for identifing and storing logs.
Note: If it is possible, please perform Squash merge type.
=> Add .uuid field to Log class

.readthedocs.yaml
This adds the RTD configuration file as discussed in #168 in an attempt to fix the documentation builds.
=> Read the Docs configuration file

.readthedocs.yaml
Format specification is not part of the Sphinx configuration block.
=> RTD: fix formats specification

pycaching/cache.py, pycaching/geocaching.py
Replaces the deprecated `text=` argument for BeautifulSoup4 with the recommended replacement `string=`. An update of BeautifulSoup4 is not required for this change, as the parameter has been introduced in version 4.4.0, while we require at least version 4.9.
Fixes #189.
=> Replace deprecated argument for BeautifulSoup4

pycaching/cache.py, pycaching/geocaching.py, test/cassettes/geocaching_api_rate_limit.json, test/cassettes/geocaching_api_rate_limit_with_none.json, test/cassettes/geocaching_search_rect.json, test/test_geocaching.py
Since we can pass parameters for reversing and limiting the returned caches directly to the URL requested by `Geocaching.search_rect()`, I believe it would be helpful (at least for me) to have these parameters accessible in Python code.
I also fixed the parsing of the `userFound` property because the returned data format has changed a bit.
And, of course, I reloaded the test cartridges to reflect recent changes.
=> Fix and improve `Geocaching.search_rect()`

pycaching/geocaching.py
This PR adds an error case to handle the situation where the login page requires a CAPTCHA. If this occurs, the `errors.LoginFailedException` is raised with an appropriate message (`CAPTCHA is required to login to the site.`).
---
When a login needs CAPTCHA, there is a present `div` element with class `g-recaptcha`. So by simply checking for the presence of the mentioned element, we could distinguish between wrong login credentials and problems with CAPTCHA.
---
Related issue:
- https://github.com/tomasbedrich/pycaching/issues/157
=> Add an error case for CAPTCHA problems

README.rst, pycaching/geocaching.py, test/cassettes/geocaching_matchload.json, test/cassettes/geocaching_quick_normal.json, test/cassettes/geocaching_quick_search.json, test/test_geocaching.py
As discussed in https://github.com/tomasbedrich/pycaching/pull/151, I've deprecated the `Geocaching.search_quick()` method. I've added a temporary solution with the use of `Geocaching.search_rect()`.
I've also updated the `README.rst` to reference `Geocaching.search_rect()` for searching for caches in an area.
And last but not least, I've updated the tests for this method.
---
Related issue:
- Fixes https://github.com/tomasbedrich/pycaching/issues/153
=> Deprecate the `Geocaching.search_quick()` method

pycaching/cache.py, test/test_cache.py
As stated in issue #216, you cannot currently acces the raw HTML version of a description.
So, I'm working on adding a `html_description` attribute to the Cache object. I understand it may not work, but I'm semi-confident I understand Beautiful Soup well enough and added the right code. Bear with me though, as the code could definitely contain mistakes.
=> Adding html_description attribute to the Cache object

pycaching/geocaching.py, test/test_geocaching.py
Allow the string to be used as a `sort_by` parameter in `Geocaching.sort()` method
=> Allow the string to be used as a `sort_by` parameter in `Geocaching.sort()` method

.readthedocs.yaml
While we declared to use the version 2 format for RTD, it seems like it is not valid anymore (or has never been a valid version 2 one).
=> Update RTD configuration file structure

.readthedocs.yaml
The error message is strange:
```
Problem in your project's configuration. Invalid configuration option "build.tools.python": expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3, miniconda3-4.7, mambaforge-4.10, mambaforge-22.9), got 3
```
Apparently, the value needs to be a string, not a number: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
=> RTD: fix Python version specifier

pycaching/geocaching.py
Due to changes on the Geocaching website, iterating `my_logs()` raises an exception due to a missing query argument "guid". This is caused by an upstream change at https://www.geocaching.com/my/logs.aspx, where the format of the URL that this library uses was changed to "https://www.geocaching.com/geocache/[WP]".
This PR modifies the `my_logs()` method to use WP to find the geocache details instead of guid, which fixes the problem.
=> Fix getting user logs

pycaching/log.py, test/test_log.py
Most caches use an archive log type of "5", but some caches use an archive type of "6". Retain support for type "5" and add support for type "6".
=> Add support for archive log type "6"
